/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password/$token'
import { Route as AuthLinkRouteImport } from './routes/auth/link'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as HouseholdIdLayoutRouteImport } from './routes/$householdId/_layout'
import { Route as HouseholdIdLayoutIndexRouteImport } from './routes/$householdId/_layout/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HouseholdIdLayoutSettingsRouteImport } from './routes/$householdId/_layout/settings'
import { Route as HouseholdIdLayoutHouseholdRouteImport } from './routes/$householdId/_layout/household'
import { Route as HouseholdIdLayoutAssignmentsRouteImport } from './routes/$householdId/_layout/assignments'
import { Route as HouseholdIdLayoutAdminRouteImport } from './routes/$householdId/_layout/admin'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkRoute = AuthLinkRouteImport.update({
  id: '/auth/link',
  path: '/auth/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdIdLayoutRoute = HouseholdIdLayoutRouteImport.update({
  id: '/$householdId/_layout',
  path: '/$householdId',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdIdLayoutIndexRoute = HouseholdIdLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HouseholdIdLayoutRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdIdLayoutSettingsRoute =
  HouseholdIdLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => HouseholdIdLayoutRoute,
  } as any)
const HouseholdIdLayoutHouseholdRoute =
  HouseholdIdLayoutHouseholdRouteImport.update({
    id: '/household',
    path: '/household',
    getParentRoute: () => HouseholdIdLayoutRoute,
  } as any)
const HouseholdIdLayoutAssignmentsRoute =
  HouseholdIdLayoutAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => HouseholdIdLayoutRoute,
  } as any)
const HouseholdIdLayoutAdminRoute = HouseholdIdLayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => HouseholdIdLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/landing': typeof LandingRoute
  '/$householdId': typeof HouseholdIdLayoutRouteWithChildren
  '/api/stream': typeof ApiStreamRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/link': typeof AuthLinkRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/$householdId/admin': typeof HouseholdIdLayoutAdminRoute
  '/$householdId/assignments': typeof HouseholdIdLayoutAssignmentsRoute
  '/$householdId/household': typeof HouseholdIdLayoutHouseholdRoute
  '/$householdId/settings': typeof HouseholdIdLayoutSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$householdId/': typeof HouseholdIdLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/landing': typeof LandingRoute
  '/api/stream': typeof ApiStreamRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/link': typeof AuthLinkRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/$householdId/admin': typeof HouseholdIdLayoutAdminRoute
  '/$householdId/assignments': typeof HouseholdIdLayoutAssignmentsRoute
  '/$householdId/household': typeof HouseholdIdLayoutHouseholdRoute
  '/$householdId/settings': typeof HouseholdIdLayoutSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$householdId': typeof HouseholdIdLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/landing': typeof LandingRoute
  '/$householdId/_layout': typeof HouseholdIdLayoutRouteWithChildren
  '/api/stream': typeof ApiStreamRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/link': typeof AuthLinkRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/$householdId/_layout/admin': typeof HouseholdIdLayoutAdminRoute
  '/$householdId/_layout/assignments': typeof HouseholdIdLayoutAssignmentsRoute
  '/$householdId/_layout/household': typeof HouseholdIdLayoutHouseholdRoute
  '/$householdId/_layout/settings': typeof HouseholdIdLayoutSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$householdId/_layout/': typeof HouseholdIdLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/landing'
    | '/$householdId'
    | '/api/stream'
    | '/auth/error'
    | '/auth/link'
    | '/reset-password/$token'
    | '/reset-password'
    | '/$householdId/admin'
    | '/$householdId/assignments'
    | '/$householdId/household'
    | '/$householdId/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$householdId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/landing'
    | '/api/stream'
    | '/auth/error'
    | '/auth/link'
    | '/reset-password/$token'
    | '/reset-password'
    | '/$householdId/admin'
    | '/$householdId/assignments'
    | '/$householdId/household'
    | '/$householdId/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$householdId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/landing'
    | '/$householdId/_layout'
    | '/api/stream'
    | '/auth/error'
    | '/auth/link'
    | '/reset-password/$token'
    | '/reset-password/'
    | '/$householdId/_layout/admin'
    | '/$householdId/_layout/assignments'
    | '/$householdId/_layout/household'
    | '/$householdId/_layout/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$householdId/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LandingRoute: typeof LandingRoute
  HouseholdIdLayoutRoute: typeof HouseholdIdLayoutRouteWithChildren
  ApiStreamRoute: typeof ApiStreamRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthLinkRoute: typeof AuthLinkRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link': {
      id: '/auth/link'
      path: '/auth/link'
      fullPath: '/auth/link'
      preLoaderRoute: typeof AuthLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$householdId/_layout': {
      id: '/$householdId/_layout'
      path: '/$householdId'
      fullPath: '/$householdId'
      preLoaderRoute: typeof HouseholdIdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$householdId/_layout/': {
      id: '/$householdId/_layout/'
      path: '/'
      fullPath: '/$householdId/'
      preLoaderRoute: typeof HouseholdIdLayoutIndexRouteImport
      parentRoute: typeof HouseholdIdLayoutRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$householdId/_layout/settings': {
      id: '/$householdId/_layout/settings'
      path: '/settings'
      fullPath: '/$householdId/settings'
      preLoaderRoute: typeof HouseholdIdLayoutSettingsRouteImport
      parentRoute: typeof HouseholdIdLayoutRoute
    }
    '/$householdId/_layout/household': {
      id: '/$householdId/_layout/household'
      path: '/household'
      fullPath: '/$householdId/household'
      preLoaderRoute: typeof HouseholdIdLayoutHouseholdRouteImport
      parentRoute: typeof HouseholdIdLayoutRoute
    }
    '/$householdId/_layout/assignments': {
      id: '/$householdId/_layout/assignments'
      path: '/assignments'
      fullPath: '/$householdId/assignments'
      preLoaderRoute: typeof HouseholdIdLayoutAssignmentsRouteImport
      parentRoute: typeof HouseholdIdLayoutRoute
    }
    '/$householdId/_layout/admin': {
      id: '/$householdId/_layout/admin'
      path: '/admin'
      fullPath: '/$householdId/admin'
      preLoaderRoute: typeof HouseholdIdLayoutAdminRouteImport
      parentRoute: typeof HouseholdIdLayoutRoute
    }
  }
}

interface HouseholdIdLayoutRouteChildren {
  HouseholdIdLayoutAdminRoute: typeof HouseholdIdLayoutAdminRoute
  HouseholdIdLayoutAssignmentsRoute: typeof HouseholdIdLayoutAssignmentsRoute
  HouseholdIdLayoutHouseholdRoute: typeof HouseholdIdLayoutHouseholdRoute
  HouseholdIdLayoutSettingsRoute: typeof HouseholdIdLayoutSettingsRoute
  HouseholdIdLayoutIndexRoute: typeof HouseholdIdLayoutIndexRoute
}

const HouseholdIdLayoutRouteChildren: HouseholdIdLayoutRouteChildren = {
  HouseholdIdLayoutAdminRoute: HouseholdIdLayoutAdminRoute,
  HouseholdIdLayoutAssignmentsRoute: HouseholdIdLayoutAssignmentsRoute,
  HouseholdIdLayoutHouseholdRoute: HouseholdIdLayoutHouseholdRoute,
  HouseholdIdLayoutSettingsRoute: HouseholdIdLayoutSettingsRoute,
  HouseholdIdLayoutIndexRoute: HouseholdIdLayoutIndexRoute,
}

const HouseholdIdLayoutRouteWithChildren =
  HouseholdIdLayoutRoute._addFileChildren(HouseholdIdLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LandingRoute: LandingRoute,
  HouseholdIdLayoutRoute: HouseholdIdLayoutRouteWithChildren,
  ApiStreamRoute: ApiStreamRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthLinkRoute: AuthLinkRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
